/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import dao.LicenciaDAO;
import dao.PersonaDAO;
import dao.TramiteDAO;
import dominio.Licencia;
import dominio.Persona;
import dominio.Placa;
import dominio.Tramite;
import interfaces.ITramiteDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hoshi
 */
public class FrHistorialLicencias extends javax.swing.JFrame {

    /**
     * Creates new form FrHistorialLicencias
     */
    Persona persona = new Persona();
    PersonaDAO personaDAO = new PersonaDAO();
    Tramite tramite = new Tramite();
    LicenciaDAO licenciaDAO = new LicenciaDAO();
    TramiteDAO tramiteDAO = new TramiteDAO();
    private List<Tramite> listaPDF;
    
    public FrHistorialLicencias(Persona persona) {
//        this.listaPDF = new ArrayList<Tramite>();

        initComponents();
        this.persona = persona;
        lblRfc.setText(persona.getRfc());
        tramite.getPersona();
        personaDAO.desencriptarPersona(persona);
         String n = persona.getNombre() + " "
                        + persona.getApellidoP() + " " + persona.getApellidoM();
         lblNombrePersona.setText(n);
            buscarTramites();
    }
    
       public void buscarTramites(){
//        ITramiteDAO tramiteDAO = new TramiteDAO();
        listaPDF= tramiteDAO.listaTramiteL(tramite.getFechaExpedicion(), tramite.getFechaVencimiento(),tramite.getCosto(),tramite.getEstado());
        
//        List <Tramite> tramites2 = tramiteDAO.listaTramiteC(chLicencia.isSelected(), chLicencia.isSelected());
        
        DefaultTableModel model = (DefaultTableModel) tblResultados.getModel();
        model.setRowCount(0);
        
        if (listaPDF != null) {
            for (int i = 0; i < listaPDF.size(); i++) {
                Object [] datos = new Object[model.getColumnCount()];
                if(listaPDF.get(i) instanceof Licencia){
                    datos[0] = listaPDF.get(i).getFechaExpedicion();
                    datos[1] = listaPDF.get(i).getFechaVencimiento();
                    datos[2] = listaPDF.get(i).getEstado();
                    datos[3] = listaPDF.get(i).getCosto();
                    
                }
                
                model.addRow(datos);
            }
                
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultados = new javax.swing.JTable();
        lblHistorialLicencia = new javax.swing.JLabel();
        lblNombrePersona = new javax.swing.JLabel();
        lblRfc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha Expedición", "Fecha Vencimiento", "Estado", "Costo"
            }
        ));
        jScrollPane1.setViewportView(tblResultados);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 114, 910, 460));

        lblHistorialLicencia.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        lblHistorialLicencia.setText("HISTORIAL LICENCIA");
        getContentPane().add(lblHistorialLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));
        getContentPane().add(lblNombrePersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 200, 40));
        getContentPane().add(lblRfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, 220, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrHistorialLicencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrHistorialLicencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrHistorialLicencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrHistorialLicencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrHistorialLicencias().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHistorialLicencia;
    private javax.swing.JLabel lblNombrePersona;
    private javax.swing.JLabel lblRfc;
    private javax.swing.JTable tblResultados;
    // End of variables declaration//GEN-END:variables
}
