/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import encripta.Encriptar;
import dao.PersonaDAO;
import dao.TramiteDAO;
import dominio.JButtonTableCellRenderer;
import dominio.Persona;
import dominio.Tramite;
import interfaces.IPersonaDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 * Pantalla de consultas
 *
 * @author xfs85
 */
public class FrmConsultas extends javax.swing.JFrame {

    /**
     * Creates new form FrmConsultas
     */
    /**
     * JbuttonTable
     */
    JButtonTableCellRenderer buttonRenderer = new JButtonTableCellRenderer();
    /**
     * btn
     */
    JButton btn = new JButton("Seleccion");
    /**
     * lista de resultados
     */
    List<Persona> resultados = new ArrayList<>();

//    private JTable tblResultados;
    /**
     * Metodo constructor por omision
     */
    public FrmConsultas() {
        initComponents();
        buscarPersonas();
//         
        tblResultados.setDefaultRenderer(Object.class, buttonRenderer);

    }

    /**
     * Metodo que se encarga de mostrar la pantalla de persona
     */
    private void mostrarPantallaFrmPersona() {
        Persona persona = new Persona();
        this.setVisible(false);
        FrmPersona frmPersona = new FrmPersona(persona);
        frmPersona.setVisible(true);
        this.dispose();
    }

    /**
     * Metodo que se encarga de buscar personas a consultar
     */
    private void buscarPersonas() {
        String busqueda = txtBusqueda.getText();
        IPersonaDAO personaDAO = new PersonaDAO();
        resultados = personaDAO.listaPersonas();

        resultados = personaDAO.desencriptarPersonaLista(resultados);
        // Realizar la consulta utilizando CriteriaBuilder según la opción seleccionada en cmbSeleccion
        if (cmbSeleccion.getSelectedItem().equals("nombre")) {
//             resultados = personaDAO.buscarNombre(busqueda);

            if (!txtBusqueda.getText().equals("")) {

                List<Persona> listaNombre = new ArrayList<Persona>();

                for (Persona p : resultados) {
                    String n = p.getNombre() + " "
                            + p.getApellidoP() + " " + p.getApellidoM();
                    if (n.toLowerCase().contains(txtBusqueda.getText().toLowerCase())) {
                        listaNombre.add(p);
                    }

                }
                resultados = listaNombre;

            }

        } else if (cmbSeleccion.getSelectedItem().equals("rfc")) {
            resultados = personaDAO.buscarRfc(busqueda);
            resultados = personaDAO.desencriptarPersonaLista(resultados);
        } else if (cmbSeleccion.getSelectedItem().equals("fecha nacimiento")) {
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                Date fechaNacimiento = sdf.parse(busqueda);
                resultados = personaDAO.buscarFechaNacimiento(fechaNacimiento);
                resultados = personaDAO.desencriptarPersonaLista(resultados);
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null, "La fecha de nacimiento ingresada no es válida. Formato válido: yyyy-MM-dd");
            }
        }
        // Crear instancia del renderer de botón

// Agregar el renderer de botón a la última columna de la tabla
//        TableColumn column = tblResultados.getColumnModel().getColumn(tblResultados.getColumnCount() - 1);
//        column.setCellRenderer(buttonRenderer);
        // Mostrar los resultados en el JTable
        DefaultTableModel model = (DefaultTableModel) tblResultados.getModel();
//        TableColumn column = tblResultados.getColumnModel().getColumn(tblResultados.getColumnCount() - 1);
//        column.setCellRenderer(buttonRenderer);
        model.setRowCount(0);
        if (resultados != null) {
            for (Persona p : resultados) {

                String n = p.getNombre() + " "
                        + p.getApellidoP() + " " + p.getApellidoM();
                model.addRow(new Object[]{p.getFechaNa(), n, p.getRfc(), btn});

            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBusqueda = new javax.swing.JButton();
        txtBusqueda = new javax.swing.JTextField();
        btnRegresarMenu = new javax.swing.JButton();
        cmbSeleccion = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultados = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBusqueda.setBorder(null);
        btnBusqueda.setContentAreaFilled(false);
        btnBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaActionPerformed(evt);
            }
        });
        jPanel1.add(btnBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(767, 90, 30, 30));

        txtBusqueda.setBorder(null);
        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
        });
        jPanel1.add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 430, 30));

        btnRegresarMenu.setBorder(null);
        btnRegresarMenu.setContentAreaFilled(false);
        btnRegresarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 30));

        cmbSeleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "nombre", "rfc", "fecha nacimiento" }));
        jPanel1.add(cmbSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 140, 30));

        tblResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha Nacimiento", "Nombre", "Rfc", "Selección Persona"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblResultados.setColumnSelectionAllowed(true);
        tblResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblResultadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblResultados);
        tblResultados.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        tblResultados.getAccessibleContext().setAccessibleParent(tblResultados);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 860, 440));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesPantallas/Consultas.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
/**
 * Regresar al menu
 * @param evt evt
 */
    private void btnRegresarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarMenuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        FrmMenu menu = new FrmMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarMenuActionPerformed
/**
 * busca accion txt
 * @param evt evt
 */
    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaActionPerformed
/**
 * busqueda accion btn
 * @param evt evt
 */
    private void btnBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaActionPerformed
        // TODO add your handling code here:
        buscarPersonas();

    }//GEN-LAST:event_btnBusquedaActionPerformed
/**
 * a
 * @param evt evt
 */
    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
        // TODO add your handling code here:
        buscarPersonas();
    }//GEN-LAST:event_txtBusquedaKeyReleased
/**
 * tabla de resultados
 * @param evt evt
 */
    private void tblResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblResultadosMouseClicked
        // TODO add your handling code here:
        int columna;
        int row;
//        int column = tblResultados.getColumnModel().getColumnIndexAtX(evt.getX());
//        int row = evt.getY()/tblResultados.getRowHeight();
        columna = tblResultados.getColumnModel().getColumnIndexAtX(evt.getX());
        row = evt.getY() / tblResultados.getRowHeight();

        if (columna <= tblResultados.getColumnCount() && columna >= 0 && row <= tblResultados.getRowCount() && row >= 0) {
            Object objeto = tblResultados.getValueAt(row, columna);
            if (objeto instanceof JButton) {
                ((JButton) objeto).doClick();
                JButton boton = (JButton) objeto;
                if (boton.equals(btn)) {
                    this.setVisible(false);
                    FrmPersona persona = new FrmPersona(resultados.get(row));
                    persona.setVisible(true);
                    this.dispose();

                }
            }
        }


    }//GEN-LAST:event_tblResultadosMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusqueda;
    private javax.swing.JButton btnRegresarMenu;
    private javax.swing.JComboBox<String> cmbSeleccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblResultados;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables

}
