/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import encripta.Encriptar;
import dao.PersonaDAO;
import dao.TramiteDAO;
import dominio.JButtonTableCellRenderer;
import dominio.Persona;
import dominio.Tramite;
import interfaces.IPersonaDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author xfs85
 */
public class FrmConsultas extends javax.swing.JFrame {

    /**
     * Creates new form FrmConsultas
     */
              JButtonTableCellRenderer buttonRenderer = new JButtonTableCellRenderer();

//    private JTable tblResultados;
    public FrmConsultas() {
        initComponents();
        buscarPersonas();
//         buttonRenderer.addActionListener((e) -> {
//            //Importante lo que va aqui
//            //El codigo se va a ejecutar ya que se le de click al boton
//            mostrarPantallaFrmPersona();
//        });
        

      
    }

    private void mostrarPantallaFrmPersona() {
        Persona persona = new Persona();
        this.setVisible(false);
        FrmPersona frmPersona = new FrmPersona(persona);
        frmPersona.setVisible(true);
        this.dispose();
    }

    private void buscarPersonas() {
        String busqueda = txtBusqueda.getText();
        IPersonaDAO personaDAO = new PersonaDAO();
        List<Persona> resultados = new ArrayList<>();
        resultados = personaDAO.listaPersonas();
        

        resultados = personaDAO.desencriptarPersonaLista(resultados);
        // Realizar la consulta utilizando CriteriaBuilder según la opción seleccionada en cmbSeleccion
        if (cmbSeleccion.getSelectedItem().equals("nombre")) {
//             resultados = personaDAO.buscarNombre(busqueda);
            
            if (!txtBusqueda.getText().equals("")) {

                List<Persona> listaNombre = new ArrayList<Persona>();

                for (Persona p : resultados) {
                    String n = p.getNombre() + " "
                            + p.getApellidoP() + " " + p.getApellidoM();
                    if (n.toLowerCase().contains(txtBusqueda.getText().toLowerCase())) {
                        listaNombre.add(p);
                    }

                }
                resultados = listaNombre;

            }
             
        } else if (cmbSeleccion.getSelectedItem().equals("rfc")) {
            resultados = personaDAO.buscarRfc(busqueda);
            resultados = personaDAO.desencriptarPersonaLista(resultados);
        } else if (cmbSeleccion.getSelectedItem().equals("fecha nacimiento")) {
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                Date fechaNacimiento = sdf.parse(busqueda);
                resultados = personaDAO.buscarFechaNacimiento(fechaNacimiento);
                resultados = personaDAO.desencriptarPersonaLista(resultados);
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null, "La fecha de nacimiento ingresada no es válida. Formato válido: yyyy-MM-dd");
            }
        }
        // Crear instancia del renderer de botón

// Agregar el renderer de botón a la última columna de la tabla
        TableColumn column = tblResultados.getColumnModel().getColumn(tblResultados.getColumnCount() - 1);
        column.setCellRenderer(buttonRenderer);
        
        // Mostrar los resultados en el JTable
         
        DefaultTableModel model = (DefaultTableModel) tblResultados.getModel();
//        TableColumn column = tblResultados.getColumnModel().getColumn(tblResultados.getColumnCount() - 1);
//        column.setCellRenderer(buttonRenderer);
        model.setRowCount(0);
        if (resultados != null) {
            for (Persona p : resultados) {

                String n = p.getNombre() + " "
                        + p.getApellidoP() + " " + p.getApellidoM();
                model.addRow(new Object[]{p.getFechaNa(), n, p.getRfc(), new JButton("Seleccionar")});

            }
            
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBusqueda = new javax.swing.JButton();
        txtBusqueda = new javax.swing.JTextField();
        btnRegresarMenu = new javax.swing.JButton();
        cmbSeleccion = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultados = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBusqueda.setBorder(null);
        btnBusqueda.setContentAreaFilled(false);
        btnBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusquedaActionPerformed(evt);
            }
        });
        jPanel1.add(btnBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(767, 90, 30, 30));

        txtBusqueda.setBorder(null);
        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
        });
        jPanel1.add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 430, 30));

        btnRegresarMenu.setBorder(null);
        btnRegresarMenu.setContentAreaFilled(false);
        btnRegresarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 30));

        cmbSeleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "nombre", "rfc", "fecha nacimiento" }));
        jPanel1.add(cmbSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 140, 30));

        tblResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha Nacimiento", "Nombre", "Rfc", "Selección Persona"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblResultados.setColumnSelectionAllowed(true);
        tblResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblResultadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblResultados);
        tblResultados.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        tblResultados.getAccessibleContext().setAccessibleParent(tblResultados);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 860, 440));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesPantallas/Consultas.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarMenuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        FrmMenu menu = new FrmMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarMenuActionPerformed

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaActionPerformed

    private void btnBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusquedaActionPerformed
        // TODO add your handling code here:
        buscarPersonas();

    }//GEN-LAST:event_btnBusquedaActionPerformed

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
        // TODO add your handling code here:
        buscarPersonas();
    }//GEN-LAST:event_txtBusquedaKeyReleased

    private void tblResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblResultadosMouseClicked
        // TODO add your handling code here:
        
        int column = tblResultados.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/tblResultados.getRowHeight();
        
        
        
    }//GEN-LAST:event_tblResultadosMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmConsultas().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBusqueda;
    private javax.swing.JButton btnRegresarMenu;
    private javax.swing.JComboBox<String> cmbSeleccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblResultados;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables

    
}
