 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import dao.LicenciaDAO;
import dao.PersonaDAO;
import dao.PlacaDAO;
import dao.VehiculoDAO;
import dominio.Persona;
import dominio.Placa;
import dominio.Vehiculo;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import utileria.Validaciones;

/**
 * Pantalla de seleccion de tramites
 * @author xfs85
 */
public class FrmSeleccionTramite extends javax.swing.JFrame {

    /**
     * Metodo constructor
     */
    public FrmSeleccionTramite() {
        initComponents();
        //Necesito construir 4 botones
        //Dos paneles 
        
        txtRfcBuscar.setVisible(false);
        
        if(txtRfcBuscar.isShowing()){
            btnRenovacion.setVisible(false);
            btnRegistro.setVerifyInputWhenFocusTarget(false);
        }
        
        btnPersona.setVisible(false);
        btnVehiculo.setVisible(false);

        btnLicencia.setVisible(false);
        btnPlacas.setVisible(false);
    }
    /**
     * Metodo que se encarga de buscar el rfc de la persona
     * @param rfc rfc de la persona
     * @return rfc de la persona
     */
    public String buscarRfc(String rfc){
        //NO DEJAR QUE EL TXT SE PERMITAN ESCRIBIR CARACTERES NO ESPECIFICADOS FALTA
        //FORZAR AL USUARIO ESCRIBIR 13 CARACTERES LISTO
        if (txtRfcBuscar.equals(" ")) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese una palabra", "Búsqueda", JOptionPane.INFORMATION_MESSAGE);
        } else if (!txtRfcBuscar.getText().contains("13")) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese 13 carácteres", "Búsqueda", JOptionPane.INFORMATION_MESSAGE);
        }

        return rfc;
    }
    /**
     * Metodo que busca el numero de serie del vehiculo
     * @param numSerie numero de serie del vehiculo
     * @return numero de serie
     */
    public String buscarNumSerie(String numSerie){
        //NO DEJAR QUE EL TXT SE PERMITAN ESCRIBIR CARACTERES NO ESPECIFICADOS FALTA
        //FORZAR AL USUARIO ESCRIBIR 13 CARACTERES LISTO
        if (txtRfcBuscar.equals(" ")) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese una palabra", "Búsqueda", JOptionPane.INFORMATION_MESSAGE);
        } else if (!Validaciones.validarCadena(txtRfcBuscar.getText())) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese un formato valido (3 letras - 3 numeros)", "Búsqueda", JOptionPane.INFORMATION_MESSAGE);
        }

        return numSerie;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panOpciones = new javax.swing.JPanel();
        txtRfcBuscar = new javax.swing.JTextField();
        btnRegistro = new javax.swing.JButton();
        btnPlacas = new javax.swing.JButton();
        btnPersona = new javax.swing.JButton();
        btnLicencia = new javax.swing.JButton();
        btnVehiculo = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnRenovacion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(790, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panOpciones.setPreferredSize(new java.awt.Dimension(800, 600));
        panOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtRfcBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRfcBuscarKeyTyped(evt);
            }
        });
        panOpciones.add(txtRfcBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 220, 50));

        btnRegistro.setBorder(null);
        btnRegistro.setContentAreaFilled(false);
        btnRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistroMouseClicked(evt);
            }
        });
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        panOpciones.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 200, 30));

        btnPlacas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesPantallas/placas.png"))); // NOI18N
        btnPlacas.setContentAreaFilled(false);
        btnPlacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlacasActionPerformed(evt);
            }
        });
        panOpciones.add(btnPlacas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 140, -1));

        btnPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesPantallas/Persona.png"))); // NOI18N
        btnPersona.setContentAreaFilled(false);
        btnPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonaActionPerformed(evt);
            }
        });
        panOpciones.add(btnPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 140, -1));

        btnLicencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesPantallas/licencia.png"))); // NOI18N
        btnLicencia.setToolTipText("");
        btnLicencia.setContentAreaFilled(false);
        btnLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLicenciaActionPerformed(evt);
            }
        });
        panOpciones.add(btnLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 140, -1));

        btnVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesPantallas/Vehiculo.png"))); // NOI18N
        btnVehiculo.setContentAreaFilled(false);
        btnVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculoActionPerformed(evt);
            }
        });
        panOpciones.add(btnVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, 140, -1));

        btnVolver.setText("jButton1");
        btnVolver.setContentAreaFilled(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        panOpciones.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 19, 30, 40));

        btnRenovacion.setBorder(null);
        btnRenovacion.setContentAreaFilled(false);
        btnRenovacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRenovacionMouseClicked(evt);
            }
        });
        btnRenovacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRenovacionActionPerformed(evt);
            }
        });
        panOpciones.add(btnRenovacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 190, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesPantallas/Cuadro1 (1).png"))); // NOI18N
        panOpciones.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1000, -1));

        getContentPane().add(panOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 807, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
         this.setVisible(false);
         FrmMenu menu = new FrmMenu();
         menu.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnRenovacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRenovacionActionPerformed
        // TODO add your handling code here:
        
               if (!btnRenovacion.isSelected()) {
            btnLicencia.setVisible(true);
            btnPlacas.setVisible(true);
        }


        
        
    }//GEN-LAST:event_btnRenovacionActionPerformed
/**
 * Renovacion
 * @param evt evt 
 */
    private void btnRenovacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRenovacionMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnRenovacionMouseClicked
/**
 * vrhiculo 
 * @param evt evt
 */
    private void btnVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculoActionPerformed
        // TODO add your handling code here:
        //Recordar poner buscar persona por rfc con joption
       
        if (!btnVehiculo.isSelected()) {

            txtRfcBuscar.setVisible(true);
            if (!buscarRfc(txtRfcBuscar.getText()).isEmpty()) {

                PersonaDAO personaDAO = new PersonaDAO();
                //PONER TXT.GETTEXT DENTRO DE DONDE ESTAN LAS COMILLAS AHORITA LISTO

                List<Persona> persona = personaDAO.buscarRfc(txtRfcBuscar.getText());

                if (persona.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "No encontro el rfc");
                    return;
                }else{
                    JOptionPane.showMessageDialog(this, "Se encontro el rfc");
                    this.setVisible(false);
                    FrmRegistroVehiculo vehiculo = new FrmRegistroVehiculo(persona.get(0));
                    vehiculo.setVisible(true);
                    this.dispose();
                 }

            }
            

        }
     
    }//GEN-LAST:event_btnVehiculoActionPerformed
/**
 * registrar 
 * @param evt evt
 */
    private void btnRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroMouseClicked
        // TODO add your handling code here:
       
            
        
    }//GEN-LAST:event_btnRegistroMouseClicked
/**
 * registro
 * @param evt evt
 */
    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        // TODO add your handling code here:   
        
        if (!btnRegistro.isSelected()) {
            btnPersona.setVisible(true);
            
            btnVehiculo.setVisible(true);
        } 
    }//GEN-LAST:event_btnRegistroActionPerformed
/**
 * btn persona
 * @param evt evt
 */
    private void btnPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        FrmRegistroPersona registro = new FrmRegistroPersona();
        registro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPersonaActionPerformed
/**
 * btnPlacass
 * @param evt evt
 */
    private void btnPlacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlacasActionPerformed
        // TODO add your handling code here:
        
         if (!btnPlacas.isSelected()) {
             JOptionPane.showMessageDialog(this, "Ingrese su número de serie");
             
            txtRfcBuscar.setVisible(true);
            if (!buscarNumSerie(txtRfcBuscar.getText()).isEmpty()) {

                VehiculoDAO vehiculoDAO = new VehiculoDAO();
                PlacaDAO placaDAO = new PlacaDAO();
                //PONER TXT.GETTEXT DENTRO DE DONDE ESTAN LAS COMILLAS AHORITA LISTO

                List<Vehiculo> vehiculo = vehiculoDAO.buscarNumSerie(txtRfcBuscar.getText());
                
                

                if (vehiculo.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "No encontro el numero de serie");
                    return;
                } else {
                    
                    txtRfcBuscar.setVisible(true);
                    Vehiculo vehiculo1 = new Vehiculo();
                    if (!vehiculo.isEmpty()) {
                        if (vehiculo.contains("activo")) {
                            JOptionPane.showMessageDialog(this, "Ya tiene placas activas,");
                            vehiculoDAO.DesactivarPlaca(vehiculo1.getId());
                        }

                    }
                    
                    JOptionPane.showMessageDialog(this, "Se encontro el numero de serie");
                    this.setVisible(false);
                    FrmPlaca placas = new FrmPlaca("renovar",vehiculo.get(0));
                    placas.setVisible(true);
//<<<<<<< HEAD:PruebaP/src/main/java/pantallas/FrmSeleccionTramite.java
//                    FrmPlaca placa = new FrmPlaca(vehiculo.get(0));
//=======
//                    FrmPlaca placa = new  FrmPlaca(persona.get(0));
//>>>>>>> main:PruebaP/src/main/java/pantallas/SeleccionTramite.java
//                    placa.setVisible(true);
                    this.dispose();
                 }

            }
         }

    }//GEN-LAST:event_btnPlacasActionPerformed
/**
 * btnLicencia
 * @param evt evt
 */
    private void btnLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLicenciaActionPerformed
        // TODO add your handling code here:
          if (!btnLicencia.isSelected()) {

            txtRfcBuscar.setVisible(true);
            if (!buscarRfc(txtRfcBuscar.getText()).isEmpty()) {

                PersonaDAO personaDAO = new PersonaDAO();
                //PONER TXT.GETTEXT DENTRO DE DONDE ESTAN LAS COMILLAS AHORITA LISTO

                List<Persona> persona = personaDAO.buscarRfc(txtRfcBuscar.getText());

                if (persona.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "No encontro el rfc");
                    return;
                } else {
                    JOptionPane.showMessageDialog(this, "Se encontro el rfc");
                    txtRfcBuscar.setVisible(true);
                    this.setVisible(false);
                    FrmLicencia licencia = new FrmLicencia(persona.get(0));
                    licencia.setVisible(true);
                    this.dispose();
                 }

            }
         }
       
    }//GEN-LAST:event_btnLicenciaActionPerformed
/**
 * txtRfc
 * @param evt evt
 */
    private void txtRfcBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRfcBuscarKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtRfcBuscarKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLicencia;
    private javax.swing.JButton btnPersona;
    private javax.swing.JButton btnPlacas;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnRenovacion;
    private javax.swing.JButton btnVehiculo;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panOpciones;
    private javax.swing.JTextField txtRfcBuscar;
    // End of variables declaration//GEN-END:variables
}
